[mypy]
python_version = 3.11
warn_unused_ignores = True
warn_redundant_casts = True
exclude = (^|/)(venv|\.venv)/

[mypy-appium.*]
ignore_missing_imports = True

[mypy-selenium.*]
ignore_missing_imports = True
