"""Framework self-check, not an app test scenario - proves the layers
(config -> driver wrapper -> pages -> services) actually wire together
correctly, without needing a real device/Appium server. Real Appium test
scenarios (the "test script layer" - one function per docs/qa/test_cases.md
case) live in the sibling `tests/` directory instead, generated by Phase 6;
this file lives in `unittests/` to keep framework plumbing checks apart from
them.
"""

from __future__ import annotations

from unittest.mock import MagicMock, patch

from config.config import load_config
from pages.library_page import LibraryPage
from pages.settings_page import SettingsPage
from pages.system_folder_picker_page import SystemFolderPickerPage
from services.library_service import LibraryService
from services.playback_service import PlaybackService
from services.settings_service import SettingsService
from exceptions.automation_errors import ValidationError
from utils.app_util import AppUtil


def test_config_loads_and_merges_environment():
    config = load_config()
    assert config.appium_server_url == "http://127.0.0.1:4723"
    assert config.app_package == "com.joshuawallis.jwplayer"
    assert config.capabilities["appium:appPackage"] == "com.joshuawallis.jwplayer"


def test_playback_service_play_song_navigates_folders_then_taps_file():
    driver_wrapper = MagicMock()
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    service.play_song("/genre_c/artist_a/song_a.mp3")

    assert driver_wrapper.tap.call_args_list == [
        (("folder_genre_c",),),
        (("folder_artist_a",),),
        (("file_song_a",),),
    ]


def test_playback_service_play_song_with_no_folders():
    driver_wrapper = MagicMock()
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    service.play_song("song_a.mp3")

    driver_wrapper.tap.assert_called_once_with("file_song_a")


def test_playback_service_reports_paused_state():
    driver_wrapper = MagicMock()
    driver_wrapper.is_present.return_value = False  # pause_button not present -> not playing
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    assert library_page.is_playing() is False
    assert service is not None  # wiring didn't blow up constructing it


def test_playback_service_validates_song_playing():
    driver_wrapper = MagicMock()
    driver_wrapper.is_present.return_value = True  # pause_button present -> playing
    driver_wrapper.find_by.return_value.text = "seek_test"
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    service.validate_song_is_playing("seek_test")  # should not raise


def test_playback_service_get_elapsed_seconds_parses_mm_ss():
    driver_wrapper = MagicMock()
    driver_wrapper.find_by.return_value.text = "02:15"
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    assert service.get_elapsed_seconds() == 135


def test_playback_service_validates_elapsed_time_is_zero():
    driver_wrapper = MagicMock()
    driver_wrapper.find_by.return_value.text = "00:00"
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    service.validate_elapsed_time_is_zero()  # should not raise


def test_playback_service_validation_fails_when_elapsed_time_not_zero():
    driver_wrapper = MagicMock()
    driver_wrapper.find_by.return_value.text = "00:03"
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    try:
        service.validate_elapsed_time_is_zero()
        assert False, "expected ValidationError"
    except ValidationError:
        pass


def test_playback_service_validates_elapsed_time_has_advanced():
    driver_wrapper = MagicMock()
    driver_wrapper.find_by.return_value.text = "00:03"
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    service.validate_elapsed_time_has_advanced()  # should not raise


def test_playback_service_validation_fails_when_elapsed_time_has_not_advanced():
    driver_wrapper = MagicMock()
    driver_wrapper.find_by.return_value.text = "00:00"
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    try:
        service.validate_elapsed_time_has_advanced()
        assert False, "expected ValidationError"
    except ValidationError:
        pass


def test_playback_service_wait_for_elapsed_time_to_advance_polls_until_advanced():
    driver_wrapper = MagicMock()
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)
    service.get_elapsed_seconds = MagicMock(side_effect=[0, 0, 3])

    with patch("services.playback_service.time.sleep") as mock_sleep:
        service.wait_for_elapsed_time_to_advance(timeout_seconds=10, poll_interval=1)

    assert service.get_elapsed_seconds.call_count == 3
    assert mock_sleep.call_count == 2


def test_playback_service_wait_for_elapsed_time_to_advance_times_out():
    driver_wrapper = MagicMock()
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)
    service.get_elapsed_seconds = MagicMock(return_value=0)

    try:
        service.wait_for_elapsed_time_to_advance(timeout_seconds=0, poll_interval=0.01)
        assert False, "expected ValidationError"
    except ValidationError:
        pass


def test_playback_service_validation_fails_when_not_playing():
    driver_wrapper = MagicMock()
    driver_wrapper.is_present.return_value = False
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    try:
        service.validate_song_is_playing("seek_test")
        assert False, "expected ValidationError"
    except ValidationError:
        pass


def test_library_service_validates_empty_message_shown():
    driver_wrapper = MagicMock()
    driver_wrapper.find_by.return_value.text = "Please choose a root folder to get started."
    library_page = LibraryPage(driver_wrapper)
    service = LibraryService(library_page)

    service.validate_empty_library_message_shown()  # should not raise


def test_library_service_validation_fails_when_message_mismatched():
    driver_wrapper = MagicMock()
    driver_wrapper.find_by.return_value.text = "set the root folder"
    library_page = LibraryPage(driver_wrapper)
    service = LibraryService(library_page)

    try:
        service.validate_empty_library_message_shown()
        assert False, "expected ValidationError"
    except ValidationError:
        pass


def test_settings_service_reports_white_noise_state():
    driver_wrapper = MagicMock()
    driver_wrapper.is_present.return_value = True  # white_noise_pause_button present -> playing
    settings_page = SettingsPage(driver_wrapper)
    service = SettingsService(settings_page)

    service.validate_white_noise_is_playing()  # should not raise


def test_app_util_restart_app_quits_then_launches_with_pauses():
    driver_wrapper = MagicMock()
    config = MagicMock()
    app_util = AppUtil(driver_wrapper, config)

    with patch("utils.app_util.time.sleep") as mock_sleep:
        app_util.restart_app(settle_seconds=1)

    driver_wrapper.driver.terminate_app.assert_called_once_with(config.app_package)
    driver_wrapper.driver.activate_app.assert_called_once_with(config.app_package)
    assert mock_sleep.call_count == 3
    mock_sleep.assert_called_with(1)


def test_app_util_reinstall_app_removes_then_installs():
    driver_wrapper = MagicMock()
    config = MagicMock()
    app_util = AppUtil(driver_wrapper, config)

    app_util.reinstall_app("/path/to/app-debug.apk")

    driver_wrapper.driver.remove_app.assert_called_once_with(config.app_package)
    driver_wrapper.driver.install_app.assert_called_once_with("/path/to/app-debug.apk")


def test_system_folder_picker_page_navigates_and_confirms():
    driver_wrapper = MagicMock()
    picker = SystemFolderPickerPage(driver_wrapper)

    picker.navigate_to_root()
    picker.open_folder("device_farm_extra_data")
    picker.use_this_folder()
    picker.allow_access()

    driver_wrapper.tap_uiautomator.assert_any_call(
        SystemFolderPickerPage.ROOT_BREADCRUMB_SELECTOR, locator="picker root breadcrumb"
    )
    driver_wrapper.tap_uiautomator.assert_any_call(
        'new UiSelector().resourceId("android:id/title").text("device_farm_extra_data")',
        locator="picker folder row 'device_farm_extra_data'",
    )
    driver_wrapper.tap_uiautomator.assert_any_call(
        SystemFolderPickerPage.USE_THIS_FOLDER_SELECTOR, locator="USE THIS FOLDER button"
    )
    driver_wrapper.tap_uiautomator.assert_any_call(SystemFolderPickerPage.ALLOW_SELECTOR, locator="ALLOW button")


def test_settings_service_set_root_folder_drives_the_full_picker_flow():
    driver_wrapper = MagicMock()
    settings_page = SettingsPage(driver_wrapper)
    service = SettingsService(settings_page)

    service.set_root_folder("device_farm_extra_data")

    driver_wrapper.tap.assert_called_once_with(SettingsPage.ROOT_FOLDER_BUTTON)
    assert driver_wrapper.tap_uiautomator.call_count == 4
