"""Framework self-check, not an app test scenario - proves the layers
(config -> driver wrapper -> pages -> services) actually wire together
correctly, without needing a real device/Appium server. Real Appium test
scenarios (the "test script layer" - one function per docs/qa/test_cases.md
case) live in the sibling `tests/` directory instead, generated by Phase 6;
this file lives in `unittests/` to keep framework plumbing checks apart from
them.
"""

from __future__ import annotations

from unittest.mock import MagicMock

from config.config import load_config
from pages.library_page import LibraryPage
from pages.settings_page import SettingsPage
from services.library_service import LibraryService
from services.playback_service import PlaybackService
from services.settings_service import SettingsService
from exceptions.automation_errors import ValidationError


def test_config_loads_and_merges_environment():
    config = load_config()
    assert config.appium_server_url == "http://127.0.0.1:4723"
    assert config.app_package == "com.joshuawallis.jwplayer"
    assert config.capabilities["appium:appPackage"] == "com.joshuawallis.jwplayer"


def test_playback_service_play_song_navigates_folders_then_taps_file():
    driver_wrapper = MagicMock()
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    service.play_song("/genre_c/artist_a/song_a.mp3")

    assert driver_wrapper.tap.call_args_list == [
        (("folder_genre_c",),),
        (("folder_artist_a",),),
        (("file_song_a",),),
    ]


def test_playback_service_play_song_with_no_folders():
    driver_wrapper = MagicMock()
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    service.play_song("song_a.mp3")

    driver_wrapper.tap.assert_called_once_with("file_song_a")


def test_playback_service_reports_paused_state():
    driver_wrapper = MagicMock()
    driver_wrapper.is_present.return_value = False  # pause_button not present -> not playing
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    assert library_page.is_playing() is False
    assert service is not None  # wiring didn't blow up constructing it


def test_playback_service_validates_song_playing():
    driver_wrapper = MagicMock()
    driver_wrapper.is_present.return_value = True  # pause_button present -> playing
    driver_wrapper.find_by.return_value.text = "seek_test"
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    service.validate_song_is_playing("seek_test")  # should not raise


def test_playback_service_validation_fails_when_not_playing():
    driver_wrapper = MagicMock()
    driver_wrapper.is_present.return_value = False
    library_page = LibraryPage(driver_wrapper)
    service = PlaybackService(library_page)

    try:
        service.validate_song_is_playing("seek_test")
        assert False, "expected ValidationError"
    except ValidationError:
        pass


def test_library_service_validates_empty_message_shown():
    driver_wrapper = MagicMock()
    driver_wrapper.find_by.return_value.text = "Please choose a root folder to get started!"
    library_page = LibraryPage(driver_wrapper)
    service = LibraryService(library_page)

    service.validate_empty_library_message_shown()  # should not raise


def test_library_service_validation_fails_when_message_mismatched():
    driver_wrapper = MagicMock()
    driver_wrapper.find_by.return_value.text = "set the root folder"
    library_page = LibraryPage(driver_wrapper)
    service = LibraryService(library_page)

    try:
        service.validate_empty_library_message_shown()
        assert False, "expected ValidationError"
    except ValidationError:
        pass


def test_settings_service_reports_white_noise_state():
    driver_wrapper = MagicMock()
    driver_wrapper.is_present.return_value = True  # white_noise_pause_button present -> playing
    settings_page = SettingsPage(driver_wrapper)
    service = SettingsService(settings_page)

    service.validate_white_noise_is_playing()  # should not raise
